### ISSUE TITLE
Windows Event queries only return SpectX sample data

### ISSUE THREAD

**Issue by db-pickens** [spectx/query_pack#2]
I've modified the _include.sx file as follows in order to point it to the .evtx file I want to analyze: 

`$localhost= 'file:/Users/dpickens/Downloads/case_logs/log.evtx';       // Default localhost Security.evtx path
@evtx=LIST([
    $localhost,             // Uncomment if you wish to query localhost events.
]) 
| EVTX()
| join(@[./meta/EventID.sx] ON EventID)                 // Join EventID and EventID description
| select(TimeCreated, EventID, Event_Description, *)    // Select TimeCreated, EventID, Event_Description and all other fields
| select_remove(right_EventID)                          // Unselect right_EventID
;
`

I have also followed the following directions from the project welcome page: 
`Your demo data is boring, I need to analyze my own data! \n
Check the files in '/user/query_pack-master/apache/view/' \n
Point to your data on local or remote storage \n
Change the file path after the LIST command in the view_default.sx file \n
To access remote storage, click on "New" in the upper menu and select "Data Store"`

Now when I run the queries provided in the pack only SpectX sample data is returned.

**Comment by raido02** [comment]
Thanks for the issue.
Could it be you didn’t save the _include.sx file after uncommenting $localhost and commenting $s3_example?
We’ve updated the commenting-uncommenting-saving instructions in readme https://github.com/spectx/query_pack/blob/master/windows_events/readme.md

**Comment by db-pickens** [comment]
Thank you for your prompt response, these updated instructions have completely resolved the issue.
